# Generated by Django 5.2 on 2025-04-23 17:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_recruiter_user_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=core.models.student_resume_path),
        ),
    ]
